name: Auto Commit Images

on:
  push:
    paths:
      - 'images/**'  # 监控images目录变化
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # 关键！使用Actions自带权限

      - name: Add new images
        run: |
          git config --global user.name "amazingname91"
          git config --global user.email "1610287343@qq.com"
          git add .
          git commit -m "Auto-add images" || echo "No changes"
          git push